version: '3'

services:
  web-app:
    image: web:18-alpine3.17
    container_name: web-app
    # Set project root directory, docker image 가 빌드할 때 사용하는 파일이 이 경로 안에 모두 포함 되어 있어야 한다.
    build:
      context: ../../../
      dockerfile: docker/back/srcs/web-app/Dockerfile
    ports:
      - "8080:8080"
      - "10001:10001"
    networks:
      - back_end_net
    restart: always

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    build: ./postgres
    ports: 
      - 5432:5432
    env_file:
      - .env
    networks:
      - back_end_net
    restart: always

networks:
  back_end_net:
    driver: bridge
 