services:
  postgres:
    image: postgres:15.3-bookworm
    container_name: postgres
    build: ./postgres
    ports: 
      - 5432:5432
    env_file:
      - .env
    restart: always
  
  app:
    image: node:18.16.1-bookworm
    container_name: app
    build:
      context: ../../../
      dockerfile: ./docker/back/srcs/app/
    ports: 
      - 8080:8080
    restart: always